"use client";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { ArrowRight, BadgeCheck, Banknote, BookOpen, Building2, Home, Search, ShieldCheck, Sparkles } from "lucide-react";
import Header from "./Header";
const examples = ["청년 창업 지원","서울 월세 지원","소상공인 대출","취업 준비 교육비"];
const categories = [{label:"주거",icon:Home,tone:"mint"},{label:"창업",icon:Building2,tone:"orange"},{label:"금융",icon:Banknote,tone:"blue"},{label:"교육·취업",icon:BookOpen,tone:"violet"}];
export default function HomeSearch(){ const [query,setQuery]=useState(""); const router=useRouter(); const submit=(event:FormEvent)=>{event.preventDefault();router.push(`/search?q=${encodeURIComponent(query.trim())}`)}; return <main><Header/><section className="hero"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="eyebrow"><Sparkles size={15}/> 흩어진 정부 혜택, 한 번에</div><h1>내게 맞는 지원사업,<br/><em>검색 한 번이면 충분해요.</em></h1><p className="hero-copy">어려운 정책 용어 대신 평소 쓰는 말로 검색하세요.<br className="desktop-only"/> 자격부터 신청 방법까지 한눈에 정리해 드립니다.</p><form className="hero-search" onSubmit={submit}><Search size={25}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="어떤 지원을 찾고 계세요?" aria-label="지원사업 검색"/><button>검색하기 <ArrowRight size={19}/></button></form><div className="examples"><span>이렇게 검색해 보세요</span>{examples.map(item=><button key={item} onClick={()=>router.push(`/search?q=${encodeURIComponent(item)}`)}>{item}</button>)}</div></section><section className="category-section content-width"><div className="section-heading"><div><span>분야별 둘러보기</span><h2>어떤 도움이 필요하세요?</h2></div><a href="/search" className="text-link">전체 보기 <ArrowRight size={17}/></a></div><div className="category-grid">{categories.map(({label,icon:Icon,tone})=><button className="category-card" key={label} onClick={()=>router.push(`/search?category=${encodeURIComponent(label)}`)}><span className={`category-icon ${tone}`}><Icon/></span><strong>{label}</strong><small>지원사업 확인하기</small><ArrowRight className="card-arrow" size={18}/></button>)}</div></section><section className="trust-section"><div className="content-width trust-grid"><div className="trust-copy"><span className="section-kicker">혜택찾기의 약속</span><h2>정확한 정보만,<br/>이해하기 쉽게</h2><p>정부와 공공기관의 공식 데이터를 바탕으로<br/>복잡한 공고를 쉬운 문장으로 정리합니다.</p></div><div className="promise-list"><Promise icon={ShieldCheck} title="공식 출처를 투명하게" text="모든 사업에 데이터 출처와 공식 링크를 표시해요."/><Promise icon={BadgeCheck} title="자격 판단은 신중하게" text="관련성 높은 사업을 추천하되, 최종 자격은 공식 공고로 안내해요."/></div></div></section><footer><div className="content-width"><span className="brand footer-brand"><Sparkles size={17}/>혜택찾기</span><p>지원사업의 최종 내용과 자격은 반드시 공식 공고에서 확인해 주세요.</p><span>© 2026 혜택찾기</span></div></footer></main> }
function Promise({icon:Icon,title,text}:{icon:typeof ShieldCheck;title:string;text:string}){return <div className="promise"><span><Icon/></span><div><strong>{title}</strong><p>{text}</p></div></div>}
