import type { Program } from "./types";
// 백엔드가 실행되지 않아도 기본 화면을 확인하기 위한 프론트엔드 DEMO 데이터다.
export const fallbackPrograms: Program[] = [
  {
    id: 1,
    title: "서울시 청년월세 지원",
    organization: "서울특별시",
    summary:
      "서울에 거주하는 청년의 주거비 부담을 줄이기 위해 월세를 지원합니다.",
    benefit: "월 최대 20만원, 최대 12개월 지원",
    target: "서울 거주 만 19~39세 무주택 청년 1인 가구",
    region: "서울",
    category: "주거",
    status: "접수중",
    period: "2026.08.03 ~ 2026.09.18",
    deadline: "D-24",
    requirements: [
      "신청일 기준 서울시 거주",
      "만 19~39세 청년",
      "임차보증금 8천만원 이하",
      "기준중위소득 150% 이하",
    ],
    documents: ["임대차계약서", "월세 이체 확인증", "가족관계증명서"],
    how_to: "서울주거포털에서 온라인 신청 후 서류를 제출합니다.",
    official_url: "https://housing.seoul.go.kr",
    notice_url: "https://housing.seoul.go.kr",
    contact: "서울주택도시공사 청년월세지원센터 · 1833-2030",
    source: "공식 API",
    tags: "청년 월세 임차 주거비",
  },
  {
    id: 2,
    title: "청년창업사관학교 입교생 모집",
    organization: "중소벤처기업진흥공단",
    summary:
      "유망한 창업 아이템과 혁신 기술을 보유한 청년 창업자의 사업화를 돕습니다.",
    benefit: "사업화 자금 최대 1억원 및 창업 교육·코칭",
    target: "만 39세 이하, 창업 3년 이내 대표자",
    region: "전국",
    category: "창업",
    status: "접수중",
    period: "2026.08.10 ~ 2026.09.04",
    deadline: "D-10",
    requirements: [
      "대표자 만 39세 이하",
      "창업 후 3년 이내 기업",
      "국세·지방세 체납 사실이 없을 것",
    ],
    documents: ["사업계획서", "사업자등록증", "법인등기부등본(해당 시)"],
    how_to: "K-Startup 누리집에서 사업계획서와 증빙서류를 제출합니다.",
    official_url: "https://www.k-startup.go.kr",
    notice_url: "https://www.k-startup.go.kr",
    contact: "중소벤처기업진흥공단 · 1357",
    source: "공식 API",
    tags: "청년 창업 사업화자금",
  },
  {
    id: 3,
    title: "소상공인 정책자금 성장기반자금",
    organization: "소상공인시장진흥공단",
    summary:
      "성장 가능성이 높은 소상공인의 운영 안정과 시설 투자를 위한 저금리 융자입니다.",
    benefit: "기업당 최대 1억원 융자, 정책금리 적용",
    target: "업력 3년 이상 소상공인 또는 스마트 소상공인",
    region: "전국",
    category: "금융",
    status: "접수예정",
    period: "2026.09.01 ~ 예산 소진 시",
    deadline: "접수예정",
    requirements: ["소상공인 기준 충족", "정책자금 지원 제외 업종이 아닐 것"],
    documents: ["사업자등록증", "부가가치세 과세표준증명"],
    how_to: "소상공인정책자금 사이트에서 온라인으로 신청합니다.",
    official_url: "https://ols.semas.or.kr",
    notice_url: "https://ols.semas.or.kr",
    contact: "중소기업통합콜센터 · 1357",
    source: "DEMO",
    tags: "소상공인 대출 융자",
  },
  {
    id: 4,
    title: "국민내일배움카드",
    organization: "고용노동부",
    summary: "취업과 직무 역량 향상에 필요한 훈련비를 카드 형태로 지원합니다.",
    benefit: "5년간 300~500만원 훈련비 지원",
    target: "직업훈련이 필요한 국민 누구나(일부 제외)",
    region: "전국",
    category: "교육·취업",
    status: "상시접수",
    period: "상시 신청",
    deadline: "상시",
    requirements: [
      "직업훈련이 필요한 국민",
      "공무원·고소득 자영업자 등 일부 대상 제외",
    ],
    documents: ["신분증", "대상별 추가 증빙서류"],
    how_to: "고용24에서 온라인 신청하거나 관할 고용센터를 방문합니다.",
    official_url: "https://www.work24.go.kr",
    notice_url: "https://www.work24.go.kr",
    contact: "고용노동부 고객상담센터 · 1350",
    source: "공식 API",
    tags: "취업 교육비 직업훈련",
  },
];
